"""feat: agrega cantidades enviadas y recibidas a PedidoDetalle

Revision ID: 103598a96708
Revises: 76302c92a9f3
Create Date: 2025-10-02 09:36:02.941821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103598a96708'
down_revision = '76302c92a9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_detalle', schema='negocio') as batch_op:
        batch_op.add_column(sa.Column('cantidad_enviada', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cantidad_recibida', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('observacion_linea', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_detalle', schema='negocio') as batch_op:
        batch_op.drop_column('observacion_linea')
        batch_op.drop_column('cantidad_recibida')
        batch_op.drop_column('cantidad_enviada')

    # ### end Alembic commands ###
