"""feat: agregar relación codigo tecnico - producto

Revision ID: 182033419269
Revises: e3ceaccd1ed9
Create Date: 2025-09-25 16:47:12.142978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182033419269'
down_revision = 'e3ceaccd1ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codigos_tecnicos', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('id_producto', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['id_producto'])
        batch_op.create_foreign_key(None, 'maestro_productos', ['id_producto'], ['id_producto'], referent_schema='productos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codigos_tecnicos', schema='productos') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id_producto')

    # ### end Alembic commands ###
