"""feat: agrega det_sub_categoria a codigo_referencia

Revision ID: 26621b217fa4
Revises: 542240da8fcc
Create Date: 2025-09-22 17:18:54.068927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26621b217fa4'
down_revision = '542240da8fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codigos_referencia', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('id_det_sub_categoria', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'detalles_sub_categoria', ['id_det_sub_categoria'], ['id_det_sub_categoria'], referent_schema='productos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codigos_referencia', schema='productos') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_det_sub_categoria')

    # ### end Alembic commands ###
