"""feat: Atributos y Valores Atributos

Revision ID: 2a068bdf0d12
Revises: a020d059db68
Create Date: 2025-09-16 14:50:11.869861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a068bdf0d12'
down_revision = 'a020d059db68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valores_atributo',
    sa.Column('id_valor', sa.Integer(), nullable=False),
    sa.Column('id_atributo', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_atributo'], ['productos.atributos.id_atributo'], ),
    sa.PrimaryKeyConstraint('id_valor'),
    sa.UniqueConstraint('id_atributo', 'codigo', name='uq_atributo_codigo_valor'),
    schema='productos'
    )
    with op.batch_alter_table('atributos', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['codigo'])

    with op.batch_alter_table('atributos_asignados', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('id_valor', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'valores_atributo', ['id_valor'], ['id_valor'], referent_schema='productos')
        batch_op.drop_column('valor')

    with op.batch_alter_table('codigos_referencia', schema='productos') as batch_op:
        batch_op.create_table_comment(
        'PRODUCTO PADRE: La entidad conceptual de un repuesto.',
        existing_comment='El estándar universal de un repuesto (OEM o de mercado)'
    )

    with op.batch_alter_table('codigos_tecnicos', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=False))
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('maestro_productos', schema='productos') as batch_op:
        batch_op.alter_column('costo_base',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Costo de referencia o promedio para cálculos de precio de venta',
               existing_nullable=False)
        batch_op.alter_column('es_kit',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('maestro_productos_id_sub_categoria_fkey'), type_='foreignkey')
        batch_op.create_table_comment(
        'PRODUCTO HIJO (SKU): El producto físico y vendible en inventario.',
        existing_comment='El producto físico y vendible que tienes en inventario'
    )
        batch_op.drop_column('id_sub_categoria')
        batch_op.drop_column('descripcion_producto')

    with op.batch_alter_table('medidas', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['codigo'])

    with op.batch_alter_table('producto_proveedor', schema='productos') as batch_op:
        batch_op.create_table_comment(
        'Tabla N-M entre SKUs y Proveedores',
        existing_comment='Tabla de unión para la relación N-M entre productos y proveedores'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto_proveedor', schema='productos') as batch_op:
        batch_op.create_table_comment(
        'Tabla de unión para la relación N-M entre productos y proveedores',
        existing_comment='Tabla N-M entre SKUs y Proveedores'
    )

    with op.batch_alter_table('medidas', schema='productos') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codigo')

    with op.batch_alter_table('maestro_productos', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('descripcion_producto', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_sub_categoria', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_table_comment(
        'El producto físico y vendible que tienes en inventario',
        existing_comment='PRODUCTO HIJO (SKU): El producto físico y vendible en inventario.'
    )
        batch_op.create_foreign_key(batch_op.f('maestro_productos_id_sub_categoria_fkey'), 'sub_categorias', ['id_sub_categoria'], ['id_sub_categoria'], referent_schema='productos')
        batch_op.alter_column('es_kit',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('costo_base',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Costo de referencia o promedio para cálculos de precio de venta',
               existing_nullable=False)

    with op.batch_alter_table('codigos_tecnicos', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('tipo')

    with op.batch_alter_table('codigos_referencia', schema='productos') as batch_op:
        batch_op.create_table_comment(
        'El estándar universal de un repuesto (OEM o de mercado)',
        existing_comment='PRODUCTO PADRE: La entidad conceptual de un repuesto.'
    )

    with op.batch_alter_table('atributos_asignados', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('valor', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_valor')

    with op.batch_alter_table('atributos', schema='productos') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codigo')

    op.drop_table('valores_atributo', schema='productos')
    # ### end Alembic commands ###
