"""Creación de esquema base a partir de modelos existentes

Revision ID: 34cb039c04a8
Revises: 
Create Date: 2025-08-29 11:03:48.970081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34cb039c04a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('codigo_area', sa.String(length=20), nullable=False),
    sa.Column('nombre_area', sa.String(length=100), nullable=False),
    sa.Column('descripcion_area', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_area'),
    sa.UniqueConstraint('codigo_area'),
    schema='entidades',
    comment='Almacena las areas (Repuesto Center S.A., etc)'
    )
    op.create_table('condiciones_pago',
    sa.Column('id_condicion_pago', sa.Integer(), nullable=False),
    sa.Column('codigo_condicion_pago', sa.String(length=20), nullable=False, comment='Código de la condición de pago'),
    sa.Column('nombre_condicion_pago', sa.String(length=100), nullable=False),
    sa.Column('descripcion_condicion_pago', sa.String(length=255), nullable=True),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('ambito', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_condicion_pago'),
    sa.UniqueConstraint('codigo_condicion_pago'),
    schema='entidades',
    comment='Almacena las condiciones de pago para cada cliente'
    )
    op.create_table('empresas',
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=100), nullable=False),
    sa.Column('rut_empresa', sa.String(length=15), nullable=False),
    sa.Column('codigo_empresa', sa.String(length=20), nullable=False, comment='Código de la empresa (RC_CL, RC_PE, GH, etc)'),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_empresa'),
    sa.UniqueConstraint('codigo_empresa'),
    schema='entidades',
    comment='Almacena las empresas (Repuesto Center S.A., etc)'
    )
    with op.batch_alter_table('empresas', schema='entidades') as batch_op:
        batch_op.create_index(batch_op.f('ix_entidades_empresas_rut_empresa'), ['rut_empresa'], unique=True)

    op.create_table('listas_precios',
    sa.Column('id_lista_precios', sa.Integer(), nullable=False),
    sa.Column('codigo_lista_precios', sa.String(length=20), nullable=False, comment='Código de la lista de precios (Alpha, Beta, etc.)'),
    sa.Column('nombre_lista_precios', sa.String(length=100), nullable=False),
    sa.Column('descripcion_lista_precios', sa.String(length=255), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_lista_precios'),
    sa.UniqueConstraint('codigo_lista_precios'),
    schema='entidades',
    comment='Almacena las listas de precios para cada cliente'
    )
    op.create_table('permisos',
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('nombre_permiso', sa.String(length=100), nullable=False),
    sa.Column('descripcion_permiso', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_permiso'),
    sa.UniqueConstraint('nombre_permiso'),
    schema='entidades'
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=100), nullable=False),
    sa.Column('descripcion_rol', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol'),
    schema='entidades'
    )
    op.create_table('segmentos_cliente',
    sa.Column('id_segmento_cliente', sa.Integer(), nullable=False),
    sa.Column('codigo_segmento_cliente', sa.String(length=20), nullable=False, comment='Código del segmento de cliente (SM, L, XL VOLUMEN, XL REPOSICION)'),
    sa.Column('nombre_segmento_cliente', sa.String(length=100), nullable=False),
    sa.Column('descripcion_segmento_cliente', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_segmento_cliente'),
    sa.UniqueConstraint('codigo_segmento_cliente'),
    schema='entidades',
    comment='Clasifica clientes por su segmento (Grandes, Medianos, Pequeños, etc.)'
    )
    op.create_table('tipo_negocio',
    sa.Column('id_tipo_negocio', sa.Integer(), nullable=False),
    sa.Column('codigo_tipo_negocio', sa.String(length=25), nullable=False),
    sa.Column('nombre_tipo_negocio', sa.String(length=255), nullable=False),
    sa.Column('descripcion_tipo_negocio', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_negocio'),
    sa.UniqueConstraint('codigo_tipo_negocio'),
    schema='entidades'
    )
    op.create_table('tipos_cliente',
    sa.Column('id_tipo_cliente', sa.Integer(), nullable=False),
    sa.Column('codigo_tipo_cliente', sa.String(length=20), nullable=False, comment='Código del tipo de cliente (NAC, EXT, etc.)'),
    sa.Column('nombre_tipo_cliente', sa.String(length=100), nullable=False),
    sa.Column('descripcion_tipo_cliente', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_cliente'),
    sa.UniqueConstraint('codigo_tipo_cliente'),
    schema='entidades',
    comment='Clasifica clientes por su naturaleza (Nacional, Extranjero, etc.)'
    )
    op.create_table('paises',
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.Column('nombre_pais', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_pais'),
    schema='general'
    )
    op.create_table('canales_venta',
    sa.Column('id_canal', sa.Integer(), nullable=False),
    sa.Column('codigo_canal', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_canal'),
    sa.UniqueConstraint('codigo_canal'),
    sa.UniqueConstraint('nombre'),
    schema='negocio',
    comment='Canales de venta (B2B, Call Center, Presencial, etc.)'
    )
    op.create_table('tipos_metas',
    sa.Column('id_tipo_meta', sa.Integer(), nullable=False),
    sa.Column('codigo_meta', sa.String(length=50), nullable=False),
    sa.Column('nombre_meta', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_meta'),
    sa.UniqueConstraint('codigo_meta'),
    schema='negocio'
    )
    op.create_table('tipos_reglas',
    sa.Column('id_tipo_regla', sa.Integer(), nullable=False),
    sa.Column('codigo_tipo_regla', sa.String(length=20), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_regla'),
    sa.UniqueConstraint('codigo_tipo_regla'),
    sa.UniqueConstraint('nombre'),
    schema='negocio',
    comment='Tipos de regla del motor (precio, descuento, tope, etc.)'
    )
    op.create_table('tipos_caso',
    sa.Column('id_tipo_caso', sa.Integer(), nullable=False),
    sa.Column('codigo_tipo_caso', sa.String(length=50), nullable=False),
    sa.Column('nombre_tipo_caso', sa.String(length=100), nullable=False),
    sa.Column('descripcion_tipo_caso', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_caso'),
    sa.UniqueConstraint('codigo_tipo_caso'),
    schema='soporte',
    comment='Categoriza los casos de soporte (Instalación, Bloqueo, etc.)'
    )
    op.create_table('roles_permisos',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['entidades.permisos.id_permiso'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['entidades.roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso'),
    schema='entidades'
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('id_area', sa.Integer(), nullable=False),
    sa.Column('id_jefe_directo', sa.Integer(), nullable=True),
    sa.Column('preferencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Preferencias de UI, notificaciones, etc.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_area'], ['entidades.areas.id_area'], ),
    sa.ForeignKeyConstraint(['id_jefe_directo'], ['entidades.usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    schema='entidades'
    )
    with op.batch_alter_table('usuarios', schema='entidades') as batch_op:
        batch_op.create_index(batch_op.f('ix_entidades_usuarios_email'), ['email'], unique=True)

    op.create_table('regiones',
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.Column('nombre_region', sa.String(length=100), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['general.paises.id_pais'], ),
    sa.PrimaryKeyConstraint('id_region'),
    schema='general'
    )
    op.create_table('motor_reglas_comerciales',
    sa.Column('id_regla', sa.Integer(), nullable=False),
    sa.Column('nombre_regla', sa.String(length=255), nullable=False),
    sa.Column('id_tipo_regla', sa.Integer(), nullable=False),
    sa.Column('condiciones', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Define CUÁNDO se aplica la regla. Ej: {"canal": "B2B", "segmento": "XL"}'),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Define QUÉ sucede. Ej: {"tipo": "descuento_porcentual", "valor": 5}'),
    sa.Column('prioridad', sa.Integer(), nullable=False, comment='Para resolver conflictos entre reglas. Mayor número = mayor prioridad.'),
    sa.Column('activa', sa.Boolean(), nullable=False, comment='Si la regla está activa o no.'),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True, comment='Fecha de inicio de la regla.'),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True, comment='Fecha de fin de la regla.'),
    sa.ForeignKeyConstraint(['id_tipo_regla'], ['negocio.tipos_reglas.id_tipo_regla'], ),
    sa.PrimaryKeyConstraint('id_regla'),
    schema='negocio',
    comment='Cerebro central de reglas de negocio para precios, descuentos, etc.'
    )
    op.create_table('marcas',
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('codigo_marca', sa.String(length=30), nullable=False),
    sa.Column('nombre_marca', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True, comment='Breve descripción o eslogan de la marca.'),
    sa.Column('tier_marca', sa.String(length=50), nullable=True, comment='Tier de la marca (TIER 1, TIER 2, TIER 3, TIER 4, etc.)'),
    sa.Column('id_pais_origen', sa.Integer(), nullable=True),
    sa.Column('url_imagen', sa.String(length=255), nullable=True, comment='URL del logo de la marca'),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais_origen'], ['general.paises.id_pais'], ),
    sa.PrimaryKeyConstraint('id_marca'),
    sa.UniqueConstraint('codigo_marca'),
    schema='productos',
    comment='Marcas de los productos (RC, GH, Bosch, etc.)'
    )
    op.create_table('base_conocimiento',
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.Column('problema_frecuente', sa.String(length=255), nullable=False),
    sa.Column('solucion_detallada', sa.Text(), nullable=False, comment='Puede contener Markdown para formato enriquecido'),
    sa.Column('id_tipo_caso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_caso'], ['soporte.tipos_caso.id_tipo_caso'], ),
    sa.PrimaryKeyConstraint('id_articulo'),
    sa.UniqueConstraint('problema_frecuente'),
    schema='soporte',
    comment='Artículos para resolver problemas comunes'
    )
    op.create_table('historial_cambios',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nombre_tabla', sa.String(length=100), nullable=False),
    sa.Column('id_registro', sa.String(length=100), nullable=False),
    sa.Column('nombre_campo', sa.String(length=100), nullable=False),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('tipo_operacion', sa.String(length=20), nullable=False, comment='CREATE, UPDATE, DELETE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['entidades.usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historial'),
    schema='analitica',
    comment='Log de auditoría para cambios en tablas críticas.'
    )
    op.create_table('usuarios_roles',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['entidades.roles.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['entidades.usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol'),
    schema='entidades'
    )
    op.create_table('ciudades',
    sa.Column('id_ciudad', sa.Integer(), nullable=False),
    sa.Column('nombre_ciudad', sa.String(length=100), nullable=False),
    sa.Column('id_region', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_region'], ['general.regiones.id_region'], ),
    sa.PrimaryKeyConstraint('id_ciudad'),
    schema='general'
    )
    op.create_table('vendedores',
    sa.Column('id_vendedor', sa.Integer(), nullable=False),
    sa.Column('codigo_vendedor_sap', sa.String(length=50), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['entidades.usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_vendedor'),
    sa.UniqueConstraint('codigo_vendedor_sap'),
    sa.UniqueConstraint('id_usuario'),
    schema='negocio'
    )
    op.create_table('maestro_clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('codigo_cliente', sa.String(length=30), nullable=False),
    sa.Column('rut_cliente', sa.String(length=15), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=False),
    sa.Column('giro_economico', sa.String(length=100), nullable=True),
    sa.Column('descuento_base', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=True),
    sa.Column('linea_credito', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Cliente activo para operar. Si es False, revisar motivo_bloqueo.'),
    sa.Column('motivo_bloqueo', sa.String(length=255), nullable=True, comment='Causa del bloqueo. Si activo = True, este campo debe ser NULO.'),
    sa.Column('b2b_habilitado', sa.Boolean(), nullable=False, comment='Si la empresa cliente tiene acceso al portal B2B.'),
    sa.Column('es_vip', sa.Boolean(), nullable=False, comment='Si el cliente es VIP.'),
    sa.Column('id_tipo_cliente', sa.Integer(), nullable=False),
    sa.Column('id_segmento_cliente', sa.Integer(), nullable=False),
    sa.Column('id_tipo_negocio', sa.Integer(), nullable=False),
    sa.Column('id_lista_precios', sa.Integer(), nullable=False),
    sa.Column('id_condicion_pago', sa.Integer(), nullable=True),
    sa.Column('id_usuario_creacion', sa.Integer(), nullable=False),
    sa.Column('id_vendedor', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_condicion_pago'], ['entidades.condiciones_pago.id_condicion_pago'], ),
    sa.ForeignKeyConstraint(['id_lista_precios'], ['entidades.listas_precios.id_lista_precios'], ),
    sa.ForeignKeyConstraint(['id_segmento_cliente'], ['entidades.segmentos_cliente.id_segmento_cliente'], ),
    sa.ForeignKeyConstraint(['id_tipo_cliente'], ['entidades.tipos_cliente.id_tipo_cliente'], ),
    sa.ForeignKeyConstraint(['id_tipo_negocio'], ['entidades.tipo_negocio.id_tipo_negocio'], ),
    sa.ForeignKeyConstraint(['id_usuario_creacion'], ['entidades.usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_vendedor'], ['negocio.vendedores.id_vendedor'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    schema='entidades',
    comment='Tabla central de clientes'
    )
    with op.batch_alter_table('maestro_clientes', schema='entidades') as batch_op:
        batch_op.create_index(batch_op.f('ix_entidades_maestro_clientes_codigo_cliente'), ['codigo_cliente'], unique=True)
        batch_op.create_index(batch_op.f('ix_entidades_maestro_clientes_nombre_cliente'), ['nombre_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_entidades_maestro_clientes_rut_cliente'), ['rut_cliente'], unique=True)

    op.create_table('comunas',
    sa.Column('id_comuna', sa.Integer(), nullable=False),
    sa.Column('nombre_comuna', sa.String(length=100), nullable=False),
    sa.Column('id_ciudad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ciudad'], ['general.ciudades.id_ciudad'], ),
    sa.PrimaryKeyConstraint('id_comuna'),
    schema='general'
    )
    op.create_table('metas',
    sa.Column('id_meta', sa.Integer(), nullable=False),
    sa.Column('periodo_anio', sa.Integer(), nullable=False),
    sa.Column('periodo_mes', sa.Integer(), nullable=False),
    sa.Column('valor_objetivo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_alcanzado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('monto_comision', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_vendedor', sa.Integer(), nullable=False),
    sa.Column('id_tipo_meta', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_meta'], ['negocio.tipos_metas.id_tipo_meta'], ),
    sa.ForeignKeyConstraint(['id_vendedor'], ['negocio.vendedores.id_vendedor'], ),
    sa.PrimaryKeyConstraint('id_meta'),
    schema='negocio'
    )
    op.create_table('cliente_metricas',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('fecha_primera_compra', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultima_compra', sa.DateTime(), nullable=True),
    sa.Column('dias_desde_ultima_compra', sa.Integer(), nullable=True, comment='Calculado diariamente. Para segmentación RFM.'),
    sa.Column('monto_total_historico', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=True),
    sa.Column('ticket_promedio_historico', sa.Numeric(precision=12, scale=2), server_default='0.0', nullable=True),
    sa.Column('cantidad_ordenes_historico', sa.Integer(), server_default='0', nullable=True),
    sa.Column('estado_cliente', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['entidades.maestro_clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    schema='analitica',
    comment='HUB de métricas. Almacena KPIs agregados a nivel de cliente.'
    )
    op.create_table('cliente_empresa',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['entidades.maestro_clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_empresa'], ['entidades.empresas.id_empresa'], ),
    sa.PrimaryKeyConstraint('id_cliente', 'id_empresa'),
    schema='entidades'
    )
    op.create_table('contactos',
    sa.Column('id_contacto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('es_principal', sa.Boolean(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['entidades.maestro_clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_contacto'),
    schema='entidades'
    )
    op.create_table('direcciones',
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('calle', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('id_comuna', sa.Integer(), nullable=False),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('es_facturacion', sa.Boolean(), nullable=False),
    sa.Column('es_despacho', sa.Boolean(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['entidades.maestro_clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_comuna'], ['general.comunas.id_comuna'], ),
    sa.PrimaryKeyConstraint('id_direccion'),
    schema='entidades'
    )
    op.create_table('usuarios_b2b',
    sa.Column('id_usuario_b2b', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['entidades.maestro_clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_usuario_b2b'),
    sa.UniqueConstraint('usuario'),
    schema='entidades'
    )
    with op.batch_alter_table('usuarios_b2b', schema='entidades') as batch_op:
        batch_op.create_index(batch_op.f('ix_entidades_usuarios_b2b_email'), ['email'], unique=True)

    op.create_table('casos',
    sa.Column('id_caso', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'EN_PROGRESO', 'RESUELTO', 'CERRADO', name='estadocaso'), nullable=False),
    sa.Column('prioridad', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadcaso'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_usuario_creacion', sa.Integer(), nullable=False, comment='Usuario interno que registra el caso'),
    sa.Column('id_usuario_asignado', sa.Integer(), nullable=True),
    sa.Column('id_tipo_caso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['entidades.maestro_clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_tipo_caso'], ['soporte.tipos_caso.id_tipo_caso'], ),
    sa.ForeignKeyConstraint(['id_usuario_asignado'], ['entidades.usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_creacion'], ['entidades.usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_caso'),
    schema='soporte',
    comment='Ticket o solicitud central de un cliente'
    )
    op.create_table('cliente_actividad',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('ultimo_login_b2b', sa.DateTime(), nullable=True),
    sa.Column('sesiones_b2b_ultimos_30d', sa.Integer(), nullable=True),
    sa.Column('sesiones_b2b_total', sa.Integer(), nullable=True),
    sa.Column('busquedas_sin_resultado_ultimos_30d', sa.Integer(), nullable=True),
    sa.Column('busquedas_sin_resultado_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['analitica.cliente_metricas.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    schema='analitica',
    comment='SPOKE. Registros de actividad y engagement del cliente.'
    )
    op.create_table('cliente_metricas_canal',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_canal', sa.Integer(), nullable=False),
    sa.Column('monto_total_canal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ticket_promedio_canal', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cantidad_ordenes_canal', sa.Integer(), nullable=True),
    sa.Column('fecha_ultima_compra_canal', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_canal'], ['negocio.canales_venta.id_canal'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['analitica.cliente_metricas.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_cliente', 'id_canal', name='pk_cliente_canal'),
    schema='analitica',
    comment='SPOKE. KPIs de un cliente por cada canal de venta.'
    )
    op.create_table('cliente_metricas_marca',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('monto_total_marca', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cantidad_productos_marca', sa.Integer(), nullable=True),
    sa.Column('ticket_promedio_marca', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_ultima_compra_marca', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['analitica.cliente_metricas.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_marca'], ['productos.marcas.id_marca'], ),
    sa.PrimaryKeyConstraint('id_cliente', 'id_marca', name='pk_cliente_marca'),
    schema='analitica',
    comment='SPOKE. KPIs de un cliente por cada marca.'
    )
    op.create_table('cliente_metricas_mensuales',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False, comment='Ej: 2025'),
    sa.Column('mes', sa.SmallInteger(), nullable=False, comment='Ej: 8 para Agosto'),
    sa.Column('monto_total_mes', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ordenes_mes', sa.Integer(), nullable=True),
    sa.Column('ticket_promedio_mes', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['analitica.cliente_metricas.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_cliente', 'anio', 'mes', name='pk_cliente_mes'),
    schema='analitica',
    comment='SPOKE. KPIs mensuales de un cliente para análisis de tendencias.'
    )
    op.create_table('equipos',
    sa.Column('id_equipo', sa.Integer(), nullable=False),
    sa.Column('id_usuario_b2b', sa.Integer(), nullable=False),
    sa.Column('nombre_equipo', sa.String(length=100), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True, comment='Dirección MAC del dispositivo'),
    sa.Column('procesador', sa.String(length=100), nullable=True),
    sa.Column('placa_madre', sa.String(length=100), nullable=True),
    sa.Column('disco_duro', sa.String(length=100), nullable=True),
    sa.Column('estado_alta', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaltaequipo'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_b2b'], ['entidades.usuarios_b2b.id_usuario_b2b'], ),
    sa.PrimaryKeyConstraint('id_equipo'),
    schema='entidades',
    comment='Equipos de clientes autorizados para operar con el B2B'
    )
    op.create_table('casos_conocimiento',
    sa.Column('id_caso', sa.Integer(), nullable=False),
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_articulo'], ['soporte.base_conocimiento.id_articulo'], ),
    sa.ForeignKeyConstraint(['id_caso'], ['soporte.casos.id_caso'], ),
    sa.PrimaryKeyConstraint('id_caso', 'id_articulo'),
    schema='soporte'
    )
    op.create_table('instalaciones',
    sa.Column('id_instalacion', sa.Integer(), nullable=False),
    sa.Column('id_caso', sa.Integer(), nullable=False),
    sa.Column('id_usuario_b2b', sa.Integer(), nullable=True, comment='Usuario B2B a instalar'),
    sa.Column('id_equipo', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True, comment='Fecha de aprobación de Gerencia'),
    sa.Column('fecha_creacion_usuario', sa.DateTime(), nullable=True, comment='Fecha de creación del usuario en el sistema'),
    sa.Column('fecha_instalacion', sa.DateTime(), nullable=True, comment='Fecha de instalación en el equipo del cliente'),
    sa.Column('fecha_capacitacion', sa.DateTime(), nullable=True, comment='Fecha de la capacitación (opcional)'),
    sa.Column('fecha_finalizacion', sa.DateTime(), nullable=True, comment='Fecha de cierre del proceso completo'),
    sa.Column('id_usuario_asignado', sa.Integer(), nullable=True, comment='Usuario asignado a la instalación'),
    sa.Column('estado', sa.Enum('PENDIENTE_APROBACION', 'PENDIENTE_INSTALACION', 'AGENDADA', 'COMPLETADA', 'CANCELADA', name='estadoinstalacion'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True, comment='Observaciones del proceso'),
    sa.ForeignKeyConstraint(['id_caso'], ['soporte.casos.id_caso'], ),
    sa.ForeignKeyConstraint(['id_equipo'], ['entidades.equipos.id_equipo'], ),
    sa.ForeignKeyConstraint(['id_usuario_asignado'], ['entidades.usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_b2b'], ['entidades.usuarios_b2b.id_usuario_b2b'], ),
    sa.PrimaryKeyConstraint('id_instalacion'),
    schema='soporte',
    comment='Registra el flujo de trabajo de una instalación específica'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instalaciones', schema='soporte')
    op.drop_table('casos_conocimiento', schema='soporte')
    op.drop_table('equipos', schema='entidades')
    op.drop_table('cliente_metricas_mensuales', schema='analitica')
    op.drop_table('cliente_metricas_marca', schema='analitica')
    op.drop_table('cliente_metricas_canal', schema='analitica')
    op.drop_table('cliente_actividad', schema='analitica')
    op.drop_table('casos', schema='soporte')
    with op.batch_alter_table('usuarios_b2b', schema='entidades') as batch_op:
        batch_op.drop_index(batch_op.f('ix_entidades_usuarios_b2b_email'))

    op.drop_table('usuarios_b2b', schema='entidades')
    op.drop_table('direcciones', schema='entidades')
    op.drop_table('contactos', schema='entidades')
    op.drop_table('cliente_empresa', schema='entidades')
    op.drop_table('cliente_metricas', schema='analitica')
    op.drop_table('metas', schema='negocio')
    op.drop_table('comunas', schema='general')
    with op.batch_alter_table('maestro_clientes', schema='entidades') as batch_op:
        batch_op.drop_index(batch_op.f('ix_entidades_maestro_clientes_rut_cliente'))
        batch_op.drop_index(batch_op.f('ix_entidades_maestro_clientes_nombre_cliente'))
        batch_op.drop_index(batch_op.f('ix_entidades_maestro_clientes_codigo_cliente'))

    op.drop_table('maestro_clientes', schema='entidades')
    op.drop_table('vendedores', schema='negocio')
    op.drop_table('ciudades', schema='general')
    op.drop_table('usuarios_roles', schema='entidades')
    op.drop_table('historial_cambios', schema='analitica')
    op.drop_table('base_conocimiento', schema='soporte')
    op.drop_table('marcas', schema='productos')
    op.drop_table('motor_reglas_comerciales', schema='negocio')
    op.drop_table('regiones', schema='general')
    with op.batch_alter_table('usuarios', schema='entidades') as batch_op:
        batch_op.drop_index(batch_op.f('ix_entidades_usuarios_email'))

    op.drop_table('usuarios', schema='entidades')
    op.drop_table('roles_permisos', schema='entidades')
    op.drop_table('tipos_caso', schema='soporte')
    op.drop_table('tipos_reglas', schema='negocio')
    op.drop_table('tipos_metas', schema='negocio')
    op.drop_table('canales_venta', schema='negocio')
    op.drop_table('paises', schema='general')
    op.drop_table('tipos_cliente', schema='entidades')
    op.drop_table('tipo_negocio', schema='entidades')
    op.drop_table('segmentos_cliente', schema='entidades')
    op.drop_table('roles', schema='entidades')
    op.drop_table('permisos', schema='entidades')
    op.drop_table('listas_precios', schema='entidades')
    with op.batch_alter_table('empresas', schema='entidades') as batch_op:
        batch_op.drop_index(batch_op.f('ix_entidades_empresas_rut_empresa'))

    op.drop_table('empresas', schema='entidades')
    op.drop_table('condiciones_pago', schema='entidades')
    op.drop_table('areas', schema='entidades')
    # ### end Alembic commands ###
