"""feat: agrega modelos de pedidos y estados maestros

Revision ID: 4ead0e073df4
Revises: 9460f2f3b73d
Create Date: 2025-09-11 14:14:00.658376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ead0e073df4'
down_revision = '9460f2f3b73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_credito',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('codigo_estado', sa.String(length=50), nullable=False),
    sa.Column('nombre_estado', sa.String(length=100), nullable=False),
    sa.Column('descripcion_estado', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_estado'),
    sa.UniqueConstraint('codigo_estado'),
    schema='negocio',
    comment='Estados de la aprobación de crédito'
    )
    op.create_table('estados_logisticos',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('codigo_estado', sa.String(length=50), nullable=False),
    sa.Column('nombre_estado', sa.String(length=100), nullable=False),
    sa.Column('descripcion_estado', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_estado'),
    sa.UniqueConstraint('codigo_estado'),
    schema='negocio',
    comment='Estados del flujo logístico'
    )
    op.create_table('estados_pedido',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('codigo_estado', sa.String(length=50), nullable=False),
    sa.Column('nombre_estado', sa.String(length=100), nullable=False),
    sa.Column('descripcion_estado', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_estado'),
    sa.UniqueConstraint('codigo_estado'),
    schema='negocio',
    comment='Estados generales de los pedidos'
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('codigo_pedido_origen', sa.String(length=50), nullable=True),
    sa.Column('numero_pedido_sap', sa.String(length=50), nullable=True),
    sa.Column('numero_factura_sap', sa.String(length=50), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_usuario_b2b', sa.Integer(), nullable=True, comment='Si el pedido fue creado por un usuario B2B'),
    sa.Column('id_vendedor', sa.Integer(), nullable=True),
    sa.Column('id_canal_venta', sa.Integer(), nullable=False),
    sa.Column('id_estado_general', sa.Integer(), nullable=False),
    sa.Column('id_estado_credito', sa.Integer(), nullable=False),
    sa.Column('id_estado_logistico', sa.Integer(), nullable=True),
    sa.Column('monto_neto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monto_impuestos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_canal_venta'], ['negocio.canales_venta.id_canal'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['entidades.maestro_clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_estado_credito'], ['negocio.estados_credito.id_estado'], ),
    sa.ForeignKeyConstraint(['id_estado_general'], ['negocio.estados_pedido.id_estado'], ),
    sa.ForeignKeyConstraint(['id_estado_logistico'], ['negocio.estados_logisticos.id_estado'], ),
    sa.ForeignKeyConstraint(['id_usuario_b2b'], ['entidades.usuarios_b2b.id_usuario_b2b'], ),
    sa.ForeignKeyConstraint(['id_vendedor'], ['negocio.vendedores.id_vendedor'], ),
    sa.PrimaryKeyConstraint('id_pedido'),
    schema='negocio',
    comment='Encabezado y estado de los pedidos'
    )
    with op.batch_alter_table('pedidos', schema='negocio') as batch_op:
        batch_op.create_index(batch_op.f('ix_negocio_pedidos_codigo_pedido_origen'), ['codigo_pedido_origen'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocio_pedidos_numero_factura_sap'), ['numero_factura_sap'], unique=False)
        batch_op.create_index(batch_op.f('ix_negocio_pedidos_numero_pedido_sap'), ['numero_pedido_sap'], unique=False)

    op.create_table('historial_estados_pedido',
    sa.Column('id_historial', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('fecha_evento', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_usuario_responsable', sa.Integer(), nullable=True, comment='Usuario interno que gatilló el cambio'),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=False),
    sa.Column('tipo_estado', sa.String(length=30), nullable=False, comment="Ej: 'CREDITO', 'LOGISTICO', 'GENERAL'"),
    sa.Column('observaciones', sa.Text(), nullable=True, comment="Ej: 'Cliente paga por adelantado', 'Ruta de despacho reprogramada'"),
    sa.ForeignKeyConstraint(['id_pedido'], ['negocio.pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_usuario_responsable'], ['entidades.usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_historial'),
    schema='negocio',
    comment='Log de auditoría para cada cambio de estado del pedido'
    )
    with op.batch_alter_table('historial_estados_pedido', schema='negocio') as batch_op:
        batch_op.create_index(batch_op.f('ix_negocio_historial_estados_pedido_id_pedido'), ['id_pedido'], unique=False)

    op.create_table('pedidos_detalle',
    sa.Column('id_pedido_detalle', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descuento_aplicado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['negocio.pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.maestro_productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_pedido_detalle'),
    schema='negocio',
    comment='Lineas de productos para cada pedido'
    )
    with op.batch_alter_table('pedidos_detalle', schema='negocio') as batch_op:
        batch_op.create_index(batch_op.f('ix_negocio_pedidos_detalle_id_pedido'), ['id_pedido'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_detalle', schema='negocio') as batch_op:
        batch_op.drop_index(batch_op.f('ix_negocio_pedidos_detalle_id_pedido'))

    op.drop_table('pedidos_detalle', schema='negocio')
    with op.batch_alter_table('historial_estados_pedido', schema='negocio') as batch_op:
        batch_op.drop_index(batch_op.f('ix_negocio_historial_estados_pedido_id_pedido'))

    op.drop_table('historial_estados_pedido', schema='negocio')
    with op.batch_alter_table('pedidos', schema='negocio') as batch_op:
        batch_op.drop_index(batch_op.f('ix_negocio_pedidos_numero_pedido_sap'))
        batch_op.drop_index(batch_op.f('ix_negocio_pedidos_numero_factura_sap'))
        batch_op.drop_index(batch_op.f('ix_negocio_pedidos_codigo_pedido_origen'))

    op.drop_table('pedidos', schema='negocio')
    op.drop_table('estados_pedido', schema='negocio')
    op.drop_table('estados_logisticos', schema='negocio')
    op.drop_table('estados_credito', schema='negocio')
    # ### end Alembic commands ###
