"""agrega unique a nombre_pais

Revision ID: 542240da8fcc
Revises: f8a4a7ee969f
Create Date: 2025-09-22 14:12:47.901941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '542240da8fcc'
down_revision = 'f8a4a7ee969f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paises', schema='general') as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_pais'])

    with op.batch_alter_table('marcas', schema='productos') as batch_op:
        batch_op.alter_column('ambito_marca',
               existing_type=postgresql.ENUM('VEHICULO', 'REPUESTO', 'MIXTO', name='ambitomarca'),
               comment='Define si la marca es de Vehículos, Repuestos o Mixta',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marcas', schema='productos') as batch_op:
        batch_op.alter_column('ambito_marca',
               existing_type=postgresql.ENUM('VEHICULO', 'REPUESTO', 'MIXTO', name='ambitomarca'),
               comment=None,
               existing_comment='Define si la marca es de Vehículos, Repuestos o Mixta',
               existing_nullable=False)

    with op.batch_alter_table('paises', schema='general') as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
