"""feat: agrega modelos de clasificacion servicio y estadistica

Revision ID: 716e2cce4dd6
Revises: 26621b217fa4
Create Date: 2025-09-23 11:54:52.775251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716e2cce4dd6'
down_revision = '26621b217fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasificaciones_estadistica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre'),
    schema='productos'
    )
    op.create_table('clasificaciones_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('nombre'),
    schema='productos'
    )
    with op.batch_alter_table('codigos_referencia', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('id_clasificacion_servicio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_clasificacion_estadistica', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'clasificaciones_servicio', ['id_clasificacion_servicio'], ['id'], referent_schema='productos')
        batch_op.create_foreign_key(None, 'clasificaciones_estadistica', ['id_clasificacion_estadistica'], ['id'], referent_schema='productos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codigos_referencia', schema='productos') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_clasificacion_estadistica')
        batch_op.drop_column('id_clasificacion_servicio')

    op.drop_table('clasificaciones_servicio', schema='productos')
    op.drop_table('clasificaciones_estadistica', schema='productos')
    # ### end Alembic commands ###
