"""feat: expande el flujo logistico y añade campos de facturacion a pedidos

Revision ID: 76302c92a9f3
Revises: ff1079b68247
Create Date: 2025-10-01 09:46:08.746363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76302c92a9f3'
down_revision = 'ff1079b68247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema='negocio') as batch_op:
        batch_op.add_column(sa.Column('factura_manual', sa.Boolean(), nullable=True, comment='True si la factura fue manual, False si fue automática'))
        batch_op.add_column(sa.Column('fecha_facturacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema='negocio') as batch_op:
        batch_op.drop_column('fecha_facturacion')
        batch_op.drop_column('factura_manual')

    # ### end Alembic commands ###
