"""solución errores

Revision ID: 7e54c79513d1
Revises: add_categoria_tipos
Create Date: 2025-10-08 14:30:07.212004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7e54c79513d1'
down_revision = 'add_categoria_tipos'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema='entidades') as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=False, comment='Activo=True/Inactivo=False'))
        batch_op.alter_column('estado_alta',
               existing_type=postgresql.ENUM('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaltaequipo'),
               comment='Aprobado/Rechazado/Pendiente',
               existing_nullable=False)

    # No intentar modificar el enum categoria_tipo_caso, ya existe correctamente

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos', schema='entidades') as batch_op:
        batch_op.alter_column('estado_alta',
               existing_type=postgresql.ENUM('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estadoaltaequipo'),
               comment=None,
               existing_comment='Aprobado/Rechazado/Pendiente',
               existing_nullable=False)
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
