"""Agrega codigo a det_sub_categoria

Revision ID: 8c315b745e8f
Revises: 2a068bdf0d12
Create Date: 2025-09-18 14:27:06.592836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c315b745e8f'
down_revision = '2a068bdf0d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_sub_categoria', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('codigo_det_sub_categoria', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['codigo_det_sub_categoria'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalles_sub_categoria', schema='productos') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codigo_det_sub_categoria')

    # ### end Alembic commands ###
