"""Actualización modelos cursor parte 1

Revision ID: 9460f2f3b73d
Revises: 68083d2918e7
Create Date: 2025-09-08 15:40:37.697512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9460f2f3b73d'
down_revision = '68083d2918e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calidades',
    sa.Column('id_calidad', sa.Integer(), nullable=False),
    sa.Column('codigo_calidad', sa.String(length=30), nullable=False),
    sa.Column('nombre_calidad', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_calidad'),
    sa.UniqueConstraint('codigo_calidad'),
    schema='productos',
    comment='Calidades de los productos (Original, Alternativo Premium, etc.)'
    )
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('codigo_categoria', sa.String(length=20), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('codigo_categoria'),
    schema='productos',
    comment='Categorías de los productos (Electrónica, Mecánica, etc.)'
    )
    op.create_table('codigos_referencia',
    sa.Column('id_codigo_referencia', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_codigo_referencia'),
    schema='productos',
    comment='El estándar universal de un repuesto (OEM o de mercado)'
    )
    with op.batch_alter_table('codigos_referencia', schema='productos') as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_codigos_referencia_codigo'), ['codigo'], unique=True)

    op.create_table('maestro_proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('codigo_proveedor', sa.String(length=50), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=150), nullable=False),
    sa.Column('rut_proveedor', sa.String(length=15), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais'], ['general.paises.id_pais'], ),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('codigo_proveedor'),
    schema='entidades',
    comment='Tabla Maestra de Proveedores'
    )
    with op.batch_alter_table('maestro_proveedores', schema='entidades') as batch_op:
        batch_op.create_index(batch_op.f('ix_entidades_maestro_proveedores_rut_proveedor'), ['rut_proveedor'], unique=True)

    op.create_table('codigos_tecnicos',
    sa.Column('id_codigo_tecnico', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('id_codigo_referencia', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_codigo_referencia'], ['productos.codigos_referencia.id_codigo_referencia'], ),
    sa.PrimaryKeyConstraint('id_codigo_tecnico'),
    sa.UniqueConstraint('codigo'),
    schema='productos',
    comment='Otros códigos estándar asociados a un código de referencia'
    )
    op.create_table('fabricas',
    sa.Column('id_fabrica', sa.Integer(), nullable=False),
    sa.Column('nombre_fabrica', sa.String(length=150), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais'], ['general.paises.id_pais'], ),
    sa.PrimaryKeyConstraint('id_fabrica'),
    sa.UniqueConstraint('nombre_fabrica'),
    schema='productos',
    comment='Fábrica o manufacturador del producto'
    )
    op.create_table('origenes',
    sa.Column('id_origen', sa.Integer(), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais'], ['general.paises.id_pais'], ),
    sa.PrimaryKeyConstraint('id_origen'),
    sa.UniqueConstraint('id_pais'),
    schema='productos',
    comment='País de origen del diseño o ingeniería del producto'
    )
    op.create_table('sub_categorias',
    sa.Column('id_sub_categoria', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('codigo_sub_categoria', sa.String(length=20), nullable=False),
    sa.Column('nombre_sub_categoria', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['productos.categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_sub_categoria'),
    sa.UniqueConstraint('codigo_sub_categoria'),
    schema='productos',
    comment='Subcategorías de las categorías (Electrónica, Mecánica, etc.)'
    )
    op.create_table('consultas',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('codigo_consulta', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Lista de etiquetas como arreglo JSON'),
    sa.Column('query_sql', sa.Text(), nullable=False, comment='Consulta SQL parametrizada. Debe ser SOLO SELECT'),
    sa.Column('parametros_defecto', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Valores por defecto para parámetros (clave->valor)'),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['entidades.usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_consulta'),
    schema='analitica',
    comment='Catálogo de consultas SQL parametrizadas para reporting (solo SELECT).'
    )
    with op.batch_alter_table('consultas', schema='analitica') as batch_op:
        batch_op.create_index(batch_op.f('ix_analitica_consultas_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_analitica_consultas_codigo_consulta'), ['codigo_consulta'], unique=True)

    op.create_table('maestro_productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('nombre_producto', sa.String(length=255), nullable=False),
    sa.Column('descripcion_producto', sa.Text(), nullable=True),
    sa.Column('id_codigo_referencia', sa.Integer(), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('id_sub_categoria', sa.Integer(), nullable=False),
    sa.Column('id_calidad', sa.Integer(), nullable=False),
    sa.Column('id_origen', sa.Integer(), nullable=True),
    sa.Column('id_fabrica', sa.Integer(), nullable=True),
    sa.Column('costo_base', sa.Numeric(precision=12, scale=2), nullable=False, comment='Costo de referencia o promedio para cálculos de precio de venta'),
    sa.Column('es_kit', sa.Boolean(), nullable=False),
    sa.Column('id_usuario_creacion', sa.Integer(), nullable=False),
    sa.Column('razon_bloqueo', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_calidad'], ['productos.calidades.id_calidad'], ),
    sa.ForeignKeyConstraint(['id_codigo_referencia'], ['productos.codigos_referencia.id_codigo_referencia'], ),
    sa.ForeignKeyConstraint(['id_fabrica'], ['productos.fabricas.id_fabrica'], ),
    sa.ForeignKeyConstraint(['id_marca'], ['productos.marcas.id_marca'], ),
    sa.ForeignKeyConstraint(['id_origen'], ['productos.origenes.id_origen'], ),
    sa.ForeignKeyConstraint(['id_sub_categoria'], ['productos.sub_categorias.id_sub_categoria'], ),
    sa.ForeignKeyConstraint(['id_usuario_creacion'], ['entidades.usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    schema='productos',
    comment='El producto físico y vendible que tienes en inventario'
    )
    with op.batch_alter_table('maestro_productos', schema='productos') as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_maestro_productos_sku'), ['sku'], unique=True)

    op.create_table('modelos',
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('nombre_modelo', sa.String(length=100), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_marca'], ['productos.marcas.id_marca'], ),
    sa.PrimaryKeyConstraint('id_modelo'),
    schema='productos'
    )
    op.create_table('consulta_ejecuciones',
    sa.Column('id_ejecucion', sa.Integer(), nullable=False),
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('ejecutada_por', sa.Integer(), nullable=True),
    sa.Column('parametros_usados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duracion_ms', sa.Integer(), nullable=True),
    sa.Column('filas', sa.Integer(), nullable=True),
    sa.Column('fecha_ejecucion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ejecutada_por'], ['entidades.usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_consulta'], ['analitica.consultas.id_consulta'], ),
    sa.PrimaryKeyConstraint('id_ejecucion'),
    schema='analitica',
    comment='Historial de ejecuciones de consultas para auditoría y performance.'
    )
    with op.batch_alter_table('consulta_ejecuciones', schema='analitica') as batch_op:
        batch_op.create_index(batch_op.f('ix_analitica_consulta_ejecuciones_id_consulta'), ['id_consulta'], unique=False)

    op.create_table('producto_proveedor',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('costo_proveedor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('codigo_producto_proveedor', sa.String(length=100), nullable=True, comment='El código que el proveedor usa para este producto'),
    sa.Column('es_proveedor_principal', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.maestro_productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['entidades.maestro_proveedores.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_producto', 'id_proveedor'),
    schema='productos',
    comment='Tabla de unión para la relación N-M entre productos y proveedores'
    )
    op.create_table('versiones_vehiculo',
    sa.Column('id_version', sa.Integer(), nullable=False),
    sa.Column('id_modelo', sa.Integer(), nullable=False),
    sa.Column('nombre_version', sa.String(length=150), nullable=False),
    sa.Column('detalle_motor', sa.String(length=100), nullable=True),
    sa.Column('cilindrada', sa.Integer(), nullable=True),
    sa.Column('anios_fabricacion', sa.ARRAY(sa.Integer()), nullable=False, comment='Lista explícita de años compatibles, ej: [2018, 2019, 2021]'),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_modelo'], ['productos.modelos.id_modelo'], ),
    sa.PrimaryKeyConstraint('id_version'),
    schema='productos'
    )
    op.create_table('aplicaciones',
    sa.Column('id_version_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_codigo_referencia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_codigo_referencia'], ['productos.codigos_referencia.id_codigo_referencia'], ),
    sa.ForeignKeyConstraint(['id_version_vehiculo'], ['productos.versiones_vehiculo.id_version'], ),
    sa.PrimaryKeyConstraint('id_version_vehiculo', 'id_codigo_referencia'),
    schema='productos',
    comment='Tabla de unión que define qué repuesto universal le sirve a qué versión de vehículo'
    )
    with op.batch_alter_table('cliente_actividad', schema='analitica') as batch_op:
        batch_op.create_table_comment(
        'SPOKE. Registros de actividad y engagement del cliente.',
        existing_comment=None
    )

    with op.batch_alter_table('cliente_metricas', schema='analitica') as batch_op:
        batch_op.alter_column('dias_desde_ultima_compra',
               existing_type=sa.INTEGER(),
               comment='Calculado diariamente. Para segmentación RFM.',
               existing_nullable=True)
        batch_op.create_table_comment(
        'HUB de métricas. Almacena KPIs agregados a nivel de cliente.',
        existing_comment='Almacena KPIs y métricas agregadas por cliente para una consulta rápida.'
    )

    with op.batch_alter_table('cliente_metricas_canal', schema='analitica') as batch_op:
        batch_op.create_table_comment(
        'SPOKE. KPIs de un cliente por cada canal de venta.',
        existing_comment=None
    )

    with op.batch_alter_table('cliente_metricas_marca', schema='analitica') as batch_op:
        batch_op.create_table_comment(
        'SPOKE. KPIs de un cliente por cada marca.',
        existing_comment=None
    )

    with op.batch_alter_table('cliente_metricas_mensuales', schema='analitica') as batch_op:
        batch_op.alter_column('anio',
               existing_type=sa.SMALLINT(),
               comment='Ej: 2025',
               existing_nullable=False)
        batch_op.alter_column('mes',
               existing_type=sa.SMALLINT(),
               comment='Ej: 8 para Agosto',
               existing_nullable=False)
        batch_op.create_table_comment(
        'SPOKE. KPIs mensuales de un cliente para análisis de tendencias.',
        existing_comment=None
    )

    with op.batch_alter_table('maestro_clientes', schema='entidades') as batch_op:
        batch_op.alter_column('es_vip',
               existing_type=sa.BOOLEAN(),
               comment='Si el cliente es VIP.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('marcas', schema='productos') as batch_op:
        batch_op.alter_column('tier_marca',
               existing_type=sa.VARCHAR(length=50),
               comment='Tier de la marca (TIER 1, TIER 2, etc.)',
               existing_comment='Tier de la marca (TIER 1, TIER 2, TIER 3, TIER 4, etc.)',
               existing_nullable=True)
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               comment='Permite desactivar un usuario sin borrarlo.',
               existing_nullable=False)
        batch_op.create_table_comment(
        'Marcas de vehículos y productos (Toyota, Bosch, etc.)',
        existing_comment=None
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marcas', schema='productos') as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Marcas de vehículos y productos (Toyota, Bosch, etc.)'
    )
        batch_op.alter_column('activo',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Permite desactivar un usuario sin borrarlo.',
               existing_nullable=False)
        batch_op.alter_column('tier_marca',
               existing_type=sa.VARCHAR(length=50),
               comment='Tier de la marca (TIER 1, TIER 2, TIER 3, TIER 4, etc.)',
               existing_comment='Tier de la marca (TIER 1, TIER 2, etc.)',
               existing_nullable=True)

    with op.batch_alter_table('maestro_clientes', schema='entidades') as batch_op:
        batch_op.alter_column('es_vip',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si el cliente es VIP.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('cliente_metricas_mensuales', schema='analitica') as batch_op:
        batch_op.drop_table_comment(
        existing_comment='SPOKE. KPIs mensuales de un cliente para análisis de tendencias.'
    )
        batch_op.alter_column('mes',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='Ej: 8 para Agosto',
               existing_nullable=False)
        batch_op.alter_column('anio',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='Ej: 2025',
               existing_nullable=False)

    with op.batch_alter_table('cliente_metricas_marca', schema='analitica') as batch_op:
        batch_op.drop_table_comment(
        existing_comment='SPOKE. KPIs de un cliente por cada marca.'
    )

    with op.batch_alter_table('cliente_metricas_canal', schema='analitica') as batch_op:
        batch_op.drop_table_comment(
        existing_comment='SPOKE. KPIs de un cliente por cada canal de venta.'
    )

    with op.batch_alter_table('cliente_metricas', schema='analitica') as batch_op:
        batch_op.create_table_comment(
        'Almacena KPIs y métricas agregadas por cliente para una consulta rápida.',
        existing_comment='HUB de métricas. Almacena KPIs agregados a nivel de cliente.'
    )
        batch_op.alter_column('dias_desde_ultima_compra',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Calculado diariamente. Para segmentación RFM.',
               existing_nullable=True)

    with op.batch_alter_table('cliente_actividad', schema='analitica') as batch_op:
        batch_op.drop_table_comment(
        existing_comment='SPOKE. Registros de actividad y engagement del cliente.'
    )

    op.drop_table('aplicaciones', schema='productos')
    op.drop_table('versiones_vehiculo', schema='productos')
    op.drop_table('producto_proveedor', schema='productos')
    with op.batch_alter_table('consulta_ejecuciones', schema='analitica') as batch_op:
        batch_op.drop_index(batch_op.f('ix_analitica_consulta_ejecuciones_id_consulta'))

    op.drop_table('consulta_ejecuciones', schema='analitica')
    op.drop_table('modelos', schema='productos')
    with op.batch_alter_table('maestro_productos', schema='productos') as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_maestro_productos_sku'))

    op.drop_table('maestro_productos', schema='productos')
    with op.batch_alter_table('consultas', schema='analitica') as batch_op:
        batch_op.drop_index(batch_op.f('ix_analitica_consultas_codigo_consulta'))
        batch_op.drop_index(batch_op.f('ix_analitica_consultas_categoria'))

    op.drop_table('consultas', schema='analitica')
    op.drop_table('sub_categorias', schema='productos')
    op.drop_table('origenes', schema='productos')
    op.drop_table('fabricas', schema='productos')
    op.drop_table('codigos_tecnicos', schema='productos')
    with op.batch_alter_table('maestro_proveedores', schema='entidades') as batch_op:
        batch_op.drop_index(batch_op.f('ix_entidades_maestro_proveedores_rut_proveedor'))

    op.drop_table('maestro_proveedores', schema='entidades')
    with op.batch_alter_table('codigos_referencia', schema='productos') as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_codigos_referencia_codigo'))

    op.drop_table('codigos_referencia', schema='productos')
    op.drop_table('categorias', schema='productos')
    op.drop_table('calidades', schema='productos')
    # ### end Alembic commands ###
