"""feat: extiende modelo de consultas con tipo y origen de bdd

Revision ID: 9e05fe9941a8
Revises: 20251013_112324
Create Date: 2025-10-17 11:25:21.134542

"""
from alembic import op
import sqlalchemy as sa
# Importante: Importar el tipo ENUM de PostgreSQL
from sqlalchemy.dialects import postgresql

# Definir los nombres de los tipos ENUM que vamos a crear
tipoquery_enum = postgresql.ENUM('LECTURA', 'ESCRITURA', 'PROCESO', name='tipoquery')
origenbdd_enum = postgresql.ENUM('RC_CORE', 'SAPB1', 'OMSRC', name='origenbdd')


# revision identifiers, used by Alembic.
revision = '9e05fe9941a8'
down_revision = '20251013_112324' # Asegúrate que este 'revises' sea el correcto para tu historial
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- PASO 1: Crear los tipos ENUM primero ---
    tipoquery_enum.create(op.get_bind())
    origenbdd_enum.create(op.get_bind())

    with op.batch_alter_table('consultas', schema='analitica') as batch_op:
        # --- PASO 2: Ahora sí, añadir las columnas usando los tipos ya creados ---
        batch_op.add_column(sa.Column('tipo', sa.Enum('LECTURA', 'ESCRITURA', 'PROCESO', name='tipoquery'), server_default='LECTURA', nullable=False))
        batch_op.add_column(sa.Column('bdd_source', sa.Enum('RC_CORE', 'SAPB1', 'OMSRC', name='origenbdd'), server_default='RC_CORE', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas', schema='analitica') as batch_op:
        batch_op.drop_column('bdd_source')
        batch_op.drop_column('tipo')

    # --- Importante: Eliminar los tipos ENUM al hacer downgrade ---
    tipoquery_enum.drop(op.get_bind())
    origenbdd_enum.drop(op.get_bind())
    
    # ### end Alembic commands ###