"""feat: Agrega modelos de productos (Division, Atributo, Medida)

Revision ID: a020d059db68
Revises: 4ead0e073df4
Create Date: 2025-09-15 15:43:45.615809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a020d059db68'
down_revision = '4ead0e073df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atributos',
    sa.Column('id_atributo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_atributo'),
    sa.UniqueConstraint('nombre'),
    schema='productos',
    comment='Atributos de los productos (Lado, Material, Color, etc.)'
    )
    op.create_table('divisiones',
    sa.Column('id_division', sa.Integer(), nullable=False),
    sa.Column('codigo_division', sa.String(length=20), nullable=False),
    sa.Column('nombre_division', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_division'),
    sa.UniqueConstraint('codigo_division'),
    schema='productos',
    comment='Divisiones de los productos (Repuestos, Accesorios, etc.)'
    )
    op.create_table('medidas',
    sa.Column('id_medida', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_medida'),
    sa.UniqueConstraint('nombre'),
    schema='productos',
    comment='Medidas de los productos (Alto, Ancho, Diámetro, etc.)'
    )
    op.create_table('detalles_sub_categoria',
    sa.Column('id_det_sub_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_det_sub_categoria', sa.String(length=100), nullable=False),
    sa.Column('id_sub_categoria', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_sub_categoria'], ['productos.sub_categorias.id_sub_categoria'], ),
    sa.PrimaryKeyConstraint('id_det_sub_categoria'),
    schema='productos',
    comment='Detalles de las subcategorías'
    )
    op.create_table('atributos_asignados',
    sa.Column('id_codigo_referencia', sa.Integer(), nullable=False),
    sa.Column('id_atributo', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_atributo'], ['productos.atributos.id_atributo'], ),
    sa.ForeignKeyConstraint(['id_codigo_referencia'], ['productos.codigos_referencia.id_codigo_referencia'], ),
    sa.PrimaryKeyConstraint('id_codigo_referencia', 'id_atributo'),
    schema='productos',
    comment='Atributos asignados a los productos'
    )
    op.create_table('medidas_asignadas',
    sa.Column('id_codigo_referencia', sa.Integer(), nullable=False),
    sa.Column('id_medida', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_codigo_referencia'], ['productos.codigos_referencia.id_codigo_referencia'], ),
    sa.ForeignKeyConstraint(['id_medida'], ['productos.medidas.id_medida'], ),
    sa.PrimaryKeyConstraint('id_codigo_referencia', 'id_medida'),
    schema='productos',
    comment='Medidas asignadas a los productos'
    )
    with op.batch_alter_table('categorias', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('id_division', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'divisiones', ['id_division'], ['id_division'], referent_schema='productos')

    with op.batch_alter_table('codigos_referencia', schema='productos') as batch_op:
        batch_op.add_column(sa.Column('id_sub_categoria', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'sub_categorias', ['id_sub_categoria'], ['id_sub_categoria'], referent_schema='productos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codigos_referencia', schema='productos') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_sub_categoria')

    with op.batch_alter_table('categorias', schema='productos') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_division')

    op.drop_table('medidas_asignadas', schema='productos')
    op.drop_table('atributos_asignados', schema='productos')
    op.drop_table('detalles_sub_categoria', schema='productos')
    op.drop_table('medidas', schema='productos')
    op.drop_table('divisiones', schema='productos')
    op.drop_table('atributos', schema='productos')
    # ### end Alembic commands ###
