"""feat_agregar_ruta_pdf_a_pedidos

Revision ID: c59d1deb5a6b
Revises: cc3be457c7c8
Create Date: 2025-10-10 09:28:36.949468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c59d1deb5a6b'
down_revision = 'cc3be457c7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema='negocio') as batch_op:
        batch_op.add_column(sa.Column('ruta_pdf', sa.String(length=500), nullable=True, comment='Ruta del PDF extraído de Gmail'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema='negocio') as batch_op:
        batch_op.drop_column('ruta_pdf')

    # ### end Alembic commands ###
