"""feat: agrega tablas de afinidad para clientes

Revision ID: cca1937f54a8
Revises: 182033419269
Create Date: 2025-09-26 14:41:27.642564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cca1937f54a8'
down_revision = '182033419269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_categorias_afinidad',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['productos.categorias.id_categoria'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['entidades.maestro_clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_cliente', 'id_categoria'),
    schema='entidades'
    )
    op.create_table('cliente_marcas_afinidad',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_marca', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['entidades.maestro_clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_marca'], ['productos.marcas.id_marca'], ),
    sa.PrimaryKeyConstraint('id_cliente', 'id_marca'),
    schema='entidades'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente_marcas_afinidad', schema='entidades')
    op.drop_table('cliente_categorias_afinidad', schema='entidades')
    # ### end Alembic commands ###
