"""feat: agrega estado activo a vendedores

Revision ID: ff1079b68247
Revises: cca1937f54a8
Create Date: 2025-09-29 11:05:21.335593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1079b68247'
down_revision = 'cca1937f54a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedores', schema='negocio') as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False, comment='Permite desactivar un usuario sin borrarlo.'))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedores', schema='negocio') as batch_op:
        batch_op.drop_column('fecha_modificacion')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
